### Create order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "price": 10000,
  "customerId": 1
}

### Get orders - Verify order status
GET http://localhost:3000/orders

### Get payments
GET http://localhost:3001/payments